#!/usr/bin/env bash
# shellcheck disable=SC2034 # Some variables may remain unused in this file.
# shellcheck source=attr.sh
# shellcheck source=boxes.sh
# shellcheck source=color.sh
# shellcheck source=cursor.sh
# shellcheck source=function.sh

# BashTerm by Jessica K McIntosh is marked CC0 1.0.
# To view a copy of this mark, visit:
# https://creativecommons.org/publicdomain/zero/1.0/

# A library of unicode box drawing characters.

# See the following resources:
# https://www.compart.com/en/unicode/block/U+2500
# https://en.wikipedia.org/wiki/Box-drawing_characters

# DO NOT EDIT THIS FILE!
# Edit the files in src/ then run the make.sh script.

# This requires bash version 4.
if [[ "${BASH_VERSINFO[0]}" -lt "4" ]] ; then
    echo "This script requires Bash 4 or later."
    echo "Current version: ${BASH_VERSION}"
    exit 1
fi

# Only load the library once.
declare -A _TERM_LOADED # Track loaded files.
declare _TERM_FILE_NAME="${BASH_SOURCE[0]##*/}"
if [[ -v _TERM_LOADED[${_TERM_FILE_NAME}] ]] ; then
    [[ -v TERM_VERBOSE ]] && echo "Already loaded '${_TERM_FILE_NAME}'."
    return 0
fi
_TERM_LOADED[${_TERM_FILE_NAME}]="${BASH_SOURCE[0]}"
[[ -v TERM_VERBOSE ]] && echo "Loading '${_TERM_FILE_NAME}'..."
unset _TERM_FILE_NAME

# Light boxes.
export TERM_BOX_LLH=$'\u2500'  # ─ Box Drawings Light Horizontal
export TERM_BOX_LLV=$'\u2502'  # │ Box Drawings Light Vertical
export TERM_BOX_LTC=$'\u252C'  # ┬ Box Drawings Light Down and Horizontal
export TERM_BOX_LTL=$'\u250C'  # ┌ Box Drawings Light Down and Right
export TERM_BOX_LTR=$'\u2510'  # ┐ Box Drawings Light Down and Left
export TERM_BOX_LML=$'\u251C'  # ├ Box Drawings Light Vertical and Right
export TERM_BOX_LMC=$'\u253C'  # ┼ Box Drawings Light Vertical and Horizontal
export TERM_BOX_LMR=$'\u2524'  # ┤ Box Drawings Light Vertical and Left
export TERM_BOX_LBC=$'\u2534'  # ┴ Box Drawings Light Up and Horizontal
export TERM_BOX_LBL=$'\u2514'  # └ Box Drawings Light Up and Right
export TERM_BOX_LBR=$'\u2518'  # ┘ Box Drawings Light Up and Left

# Heavy boxes.
export TERM_BOX_HLH=$'\u2501'  # ━ Box Drawings Heavy Horizontal
export TERM_BOX_HLV=$'\u2503'  # ┃ Box Drawings Heavy Vertical
export TERM_BOX_HTC=$'\u2533'  # ┳ Box Drawings Heavy Down and Horizontal
export TERM_BOX_HTL=$'\u250F'  # ┏ Box Drawings Heavy Down and Right
export TERM_BOX_HTR=$'\u2513'  # ┓ Box Drawings Heavy Down and Left
export TERM_BOX_HML=$'\u2523'  # ┣ Box Drawings Heavy Vertical and Right
export TERM_BOX_HMC=$'\u254B'  # ╋ Box Drawings Heavy Vertical and Horizontal
export TERM_BOX_HMR=$'\u252B'  # ┫ Box Drawings Heavy Vertical and Left
export TERM_BOX_HBC=$'\u253B'  # ┻ Box Drawings Heavy Up and Horizontal
export TERM_BOX_HBL=$'\u2517'  # ┗ Box Drawings Heavy Up and Right
export TERM_BOX_HBR=$'\u251B'  # ┛ Box Drawings Heavy Up and Left

# Double boxes.
export TERM_BOX_DLH=$'\u2550'  # ═ Box Drawings Double Horizontal
export TERM_BOX_DLV=$'\u2551'  # ║ Box Drawings Double Vertical
export TERM_BOX_DTC=$'\u2566'  # ╦ Box Drawings Double Down and Horizontal
export TERM_BOX_DTL=$'\u2554'  # ╔ Box Drawings Double Down and Right
export TERM_BOX_DTR=$'\u2557'  # ╗ Box Drawings Double Down and Left
export TERM_BOX_DML=$'\u2560'  # ╠ Box Drawings Double Vertical and Right
export TERM_BOX_DMC=$'\u256C'  # ╬ Box Drawings Double Vertical and Horizontal
export TERM_BOX_DMR=$'\u2563'  # ╣ Box Drawings Double Vertical and Left
export TERM_BOX_DBC=$'\u2569'  # ╩ Box Drawings Double Up and Horizontal
export TERM_BOX_DBL=$'\u255A'  # ╚ Box Drawings Double Up and Right
export TERM_BOX_DBR=$'\u255D'  # ╝ Box Drawings Double Up and Left

# Rounded light boxes.
export TERM_BOX_RLH=$'\u2500'  # ─ Box Drawings Light Horizontal
export TERM_BOX_RLV=$'\u2502'  # │ Box Drawings Light Vertical
export TERM_BOX_RTC=$'\u252C'  # ┬ Box Drawings Light Down and Horizontal
export TERM_BOX_RTL=$'\u256D'  # ╭ Box Drawings Light Arc Down and Right
export TERM_BOX_RTR=$'\u256E'  # ╮ Box Drawings Light Arc Down and Left
export TERM_BOX_RML=$'\u251C'  # ├ Box Drawings Light Vertical and Right
export TERM_BOX_RMC=$'\u253C'  # ┼ Box Drawings Light Vertical and Horizontal
export TERM_BOX_RMR=$'\u2524'  # ┤ Box Drawings Light Vertical and Left
export TERM_BOX_RBC=$'\u2534'  # ┴ Box Drawings Light Up and Horizontal
export TERM_BOX_RBL=$'\u2570'  # ╰ Box Drawings Light Arc Up and Right
export TERM_BOX_RBR=$'\u256F'  # ╯ Box Drawings Light Arc Up and Left

# If called directly then suggest the example.
if [[ "${0}" == "${BASH_SOURCE[0]}" ]] ; then
    declare example_file="${0##*/}"
    example_file="${example_file%.*}"
    echo "For an example try:"
    printf "./examples/%s_example.sh\n" "${example_file}"
fi
