#!/usr/bin/env bash

# BashTerm by Jessica K McIntosh is marked CC0 1.0.
# To view a copy of this mark, visit:
# https://creativecommons.org/publicdomain/zero/1.0/

# A direct interface to the terminfo description.

# For more information see:
# man 5 terminfo # Describes the capability database.
# man 3 terminfo # Describes the API.
# man 1 infocmp  # How the capabilities are retrieved.
# https://invisible-island.net/ncurses/man/terminfo.5.html
# https://github.com/ThomasDickey/ncurses-snapshots/tree/master
# I tried to match the established naming conventions.

# DO NOT EDIT THIS FILE!
# Edit the files in src/ then run the make.sh script.

# This requires bash version 4.4 or later.
if [ -z "$BASH_VERSION" ]; then
    echo "Error: Bash version 4.4 or higher is required."
    exit 1
fi
if ((BASH_VERSINFO[0] < 4)) || ((BASH_VERSINFO[0] == 4 && BASH_VERSINFO[1] < 4)); then
    echo "Error: Bash version 4.4 or higher is required."
    echo "Current version: ${BASH_VERSION}"
    exit 1
fi

# Only load the library once.
declare -A _TERM_LOADED # Track loaded files.
declare _TERM_FILE_NAME="${BASH_SOURCE[0]##*/}"
if [[ -v _TERM_LOADED[${_TERM_FILE_NAME}] ]]; then
    [[ -v TERM_VERBOSE ]] && echo "Already loaded '${_TERM_FILE_NAME}'."
    return 0
fi
_TERM_LOADED[${_TERM_FILE_NAME}]="${BASH_SOURCE[0]}"
[[ -v TERM_VERBOSE ]] && echo "Loading '${_TERM_FILE_NAME}'..."
unset _TERM_FILE_NAME

# Contains the terminfo details.
declare -A TERM_INFO

# Static variable storage file.
declare -g _TERM_INFO_VARIABLE_FILE=""

# Initialize the terminfo library.
term::info_init() {
    # Make sure infocmp is installed.
    if ! command -v infocmp > /dev/null; then
        echo "The required command 'infocmp' is not installed."
        exit 1
    fi

    # Create the storage for static variables.
    trap '[[ -n $_TERM_INFO_VARIABLE_FILE ]] && rm -f "${_TERM_INFO_VARIABLE_FILE}"' EXIT
    _TERM_INFO_VARIABLE_FILE=$(mktemp --tmpdir BashTermInfoVars.XXXXXXXXXX) || exit 1

    # Setup the terminal.
    term::setupterm || exit 1
}

# Setup the terminal.
term::setupterm() {
    local terminal=${1:-$TERM}
    local name value

    # Make sure the terminal type is valid.
    if ! TERM=${terminal} infocmp > /dev/null 2>&1; then
        echo "Invalid terminal type: ${terminal@Q}"
        return 1
    fi

    # Read the capabilities and store them into TERM_INFO.
    TERM_INFO=()
    while IFS='=' read -r name value; do
        # Strip the trailing comma.
        # Without this comma read will drop a trailing '='.
        value=${value%,}
        TERM_INFO[${name}]=${value}
    done < <(TERM=${terminal} infocmp -q -1 -l | awk -f setupterm.awk)
}

# Print the interpreted value for a terminal capability.
# Will happily print boolean or numeric capabilities.
# Returns:
#   0   Success
#   1   The capability is absent.
#       Also prints an error to STDERR.
#   2   The capability is cancelled.
term::tput() {
    local name=${1:-}
    shift
    local -a parameters=("${@}")
    local value

    if [[ -v TERM_INFO[${name}] ]]; then
        value=${TERM_INFO[${name}]}
    else
        echo "Invalid capability name ${name@Q}." 1>&2
        return 1
    fi

    # Is the capability canceled?
    if [[ ${value} == "CANCELED" ]]; then
        return 2
    fi

    # Easy case, no parameters.
    if [[ ! ${value/%/} =~ [%] ]]; then
        # shellcheck disable=SC2059 # Do it this way to escape sequences.
        printf "${value}"
        return 0
    fi

    # Parameters are required. Run it through awk.
    # shellcheck disable=SC2059 # Do it this way to escape sequences.
    printf "$(gawk -vvar_file="${_TERM_INFO_VARIABLE_FILE}" -f tparm.awk -- "${value}" "${parameters[@]}")"
}

# Prints the type for a capability.
# One of 'Boolean', 'Number', or 'String'.
term::tigettype() {
    local name=${1:-}
    local value=${TERM_INFO[${name}]}
    if [[ ${value} == "TRUE" ]]; then
        echo "Boolean"
    elif [[ ${value} =~ [#].*$ ]]; then
        echo "Number"
    else
        echo "String"
    fi
}

# Get boolean terminal capability.
# TRUE or FALSE is printed.
# Returns:
#   0   The capability is boolean and true.
#   1   The capability is cancelled or absent.
#   2   The capability is not boolean.
term::tigetflag() {
    local name=${1:-}
    local value

    if [[ -v TERM_INFO[${name}] ]]; then
        value=${TERM_INFO[${name}]}
    else
        return 1
    fi

    if [[ ${value} == "CANCELED" ]]; then
        return 1
    fi

    if [[ ${value} == "TRUE" ]]; then
        return 0
    fi

    return 2
}

# Get numeric terminal capability.
# The value is printed.
# Returns:
#   0   The capability is a number.
#   1   The capability is cancelled or absent.
#   2   The capability is not a number.
term::tigetnum() {
    local name=${1:-}
    local value

    if [[ -v TERM_INFO[${name}] ]]; then
        value=${TERM_INFO[${name}]}
    else
        return 1
    fi

    if [[ ${value} == "CANCELED" ]]; then
        return 1
    fi

    if [[ "$(term::tigettype "${name}")" != "Number" ]]; then
        return 2
    fi

    echo "${value###}"
    return 0
}

# Get a string capability.
# The value is printed.
# Returns:
#   0   The capability is a string.
#   1   The capability is cancelled or absent.
#   2   The capability is not a string.
term::tigetstr() {
    local name=${1:-}
    local value

    if [[ -v TERM_INFO[${name}] ]]; then
        value=${TERM_INFO[${name}]}
    else
        return 1
    fi

    if [[ ${value} == "CANCELED" ]]; then
        return 1
    fi

    if [[ "$(term::tigettype "${name}")" != "String" ]]; then
        return 2
    fi

    echo "${value}"
    return 0
}

term::info_test() {
    local name value my_output tput_output tput_return
    # declare -p test_list

    while IFS=$'=' read -r name value; do
        # Clear the variables to make each test independent.
        echo "" > "${_TERM_INFO_VARIABLE_FILE}"

        # Get the output to test.
        my_output="$(term::tput "${name}" 1 2 3 4 5 6 7 8 9)"
        if [[ ${name} == "clear" ]]; then
            # tput does strange things for 'clear'. :(
            tput_output="$(tput -x "${name}" | tr -d '\000')"
        else
            tput_output="$(tput "${name}" 1 2 3 4 5 6 7 8 9 2> /dev/null | tr -d '\000')"
            tput_return=$?
            if [[ ! $tput_return ]]; then
                echo "Error running 'tput ${name} 1 2 3 4 5 6 7 8 9'. Return Code: $tput_return" 1>&2
                exit 1
            fi
        fi

        if [[ ${my_output} != "${tput_output}" ]]; then
            echo "Capability ${name}=(${value}) does not match..."
            printf "Expected: "
            # shellcheck disable=SC2059
            printf "${tput_output}" | xxd
            printf "Actual  : "
            # shellcheck disable=SC2059
            printf "${my_output}" | xxd
        fi
    done < <(infocmp -q -1 -l | sed -n -e 's/^\t//;/=.*$/p')

}

term::info_init

# declare -p TERM_INFO

# term::tput "setf" "0" | xxd
# tput setf 0 | xxd
# for number in {0..9}; do
#     echo "# ${number}"
#     term::tput "setf" ${number} | xxd
#     tput setf ${number} | xxd
# done
#term::tput kf9 | xxd
#tput kf9 | xxd

echo "Running tests..."
for TERM in vt100 vt220 xterm xterm-color xterm-256color screen tmux sun amiga wy350; do
    TERM_INFO=()
    term::info_init
    echo "Terminal: ${TERM_INFO[_name]} : ${TERM_INFO[_descr]}"
    term::info_test
    echo "Done."
    echo ""
done

# echo ""
# echo "term::tigetflag am - Boolean"
# term::tigetflag am
# echo "RC=$?"
# echo ""
# echo "term::tigetflag cup - String"
# term::tigetflag cup
# echo "RC=$?"
# echo ""
# echo "term::tigetflag it - Number"
# term::tigetflag it
# echo "RC=$?"
# echo ""
# echo "term::tigetflag ZZZ - Noexistant"
# term::tigetflag ZZZ
# echo "RC=$?"

# echo ""
# echo "term::tigetnum am - Boolean"
# term::tigetnum am
# echo "RC=$?"
# echo ""
# echo "term::tigetnum cup - String"
# term::tigetnum cup
# echo "RC=$?"
# echo ""
# echo "term::tigetnum it - Number"
# term::tigetnum it
# echo "RC=$?"
# echo ""
# echo "term::tigetnum ZZZ - Noexistant"
# term::tigetnum ZZZ
# echo "RC=$?"

# echo ""
# echo "term::tigetstr am - Boolean"
# term::tigetstr am
# echo "RC=$?"
# echo ""
# echo "term::tigetstr cup - String"
# term::tigetstr cup
# echo "RC=$?"
# echo ""
# echo "term::tigetstr it - Number"
# term::tigetstr it
# echo "RC=$?"
# echo ""
# echo "term::tigetstr ZZZ - Noexistant"
# term::tigetstr ZZZ
# echo "RC=$?"
